
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np

array=np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [3]:
matrix=array.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access the element at the second row, second column.


In [4]:
matrix[1,1]

4

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [5]:
A=np.array([1, 2, 3])
B=np.array([4, 5, 6])

print("************************ PERFORM OPERATION IN MATRIXS ***********************************")

print(f"Addtion of two matrix: {np.add(A,B)}")
print(f"Subtraction of two matrix: {np.subtract(A,B)}")
print(f"Multiplication of two matrix: {np.multiply(A,B)}")
print(f"Division of two matrix: {np.divide(A,B)}")

************************ PERFORM OPERATION IN MATRIXS ***********************************
Addtion of two matrix: [5 7 9]
Subtraction of two matrix: [-3 -3 -3]
Multiplication of two matrix: [ 4 10 18]
Division of two matrix: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [6]:
array=np.array([1, 2, 3, 4, 5])

print(f"sum of the array: {np.sum(array)}")
print(f"Mean of the array: {np.mean(array)}")
print(f"standard deviation of the array: {np.std(array)}")

sum of the array: 15
Mean of the array: 3.0
standard deviation of the array: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [7]:
array=np.array([1, 2, 3, 4, 5, 6])
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [43]:
Random_integers=np.random.randint(0,10,size=[5,5])
Random_integers

array([[7, 4, 3, 8, 9],
       [0, 2, 3, 2, 1],
       [0, 1, 2, 4, 5],
       [4, 8, 5, 8, 2],
       [8, 0, 8, 7, 8]])

Replace all values in the sub-array with a specific value.


In [46]:
Row_Start, Row_End = 1, 3
Col_Start, Col_End = 2, 4

Random_integers[Row_Start:Row_End, Col_Start:Col_End] = 

print(Random_integers)

[[7 4 3 8 9]
 [0 2 2 2 1]
 [0 1 2 2 5]
 [4 8 5 8 2]
 [8 0 8 7 8]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [10]:
sub_array=np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"Extract sub array {sub_array[1]} {sub_array[3]}")

Extract sub array [3 4] [7 8]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [33]:
array_2d=np.random.randint(0,3,size=[3,3])
array_2d

array([[1, 0, 2],
       [0, 1, 1],
       [1, 0, 1]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [36]:
array_1d=np.array([0,1,2])
print("Addition of 2D and 1D array:\n",array_2d + array_1d)

Addition of 2D and 1D array:
 [[1 1 4]
 [0 2 3]
 [1 1 3]]


In [37]:
array_1d.shape

(3,)

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [17]:
a=np.random.randint(1,11,size=[3,3])
b=np.random.randint(1,11,size=[3,3])
a,b

(array([[8, 1, 4],
        [7, 1, 1],
        [5, 6, 7]]),
 array([[ 3,  9,  2],
        [ 3, 10,  4],
        [ 7,  3,  6]]))

In [18]:
Concatented_Horizontally = np.hstack((a,b))

Concatented_Vertically = np.vstack((a,b))

print("Horizontally:")
print(Concatented_Horizontally)
print("Vertically:")
print(Concatented_Vertically)

Horizontally:
[[ 8  1  4  3  9  2]
 [ 7  1  1  3 10  4]
 [ 5  6  7  7  3  6]]
Vertically:
[[ 8  1  4]
 [ 7  1  1]
 [ 5  6  7]
 [ 3  9  2]
 [ 3 10  4]
 [ 7  3  6]]


In [32]:
Original_Array1 = np.hsplit(Concatented_Horizontally,1)

Original_Array2 = np.vsplit(Concatented_Vertically,2)

print("Original Horizantel:")
print(Original_Array1[0])
print("Original Vertical):")
print(Original_Array2[1])

Original Horizantel:
[[ 8  1  4  3  9  2]
 [ 7  1  1  3 10  4]
 [ 5  6  7  7  3  6]]
Original Vertical):
[[ 3  9  2]
 [ 3 10  4]
 [ 7  3  6]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [216]:
array=[1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]
counter = 0
num = array[:]
for i in array:
    mode = array.count(i)
    if(mode> counter):
        counter = mode
        num=i

print("The mode is:",num)
print("The Number apperance:",counter)
    

The mode is: 1
The Number apperance: 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

